config/routes.rb
Rails.application.routes.draw do
  root to: 'books#index'
  resources :books, only: [:index]
  resources :carts, only: [:index], path: 'cart', as: 'cart'
  resources :cart_items, only: [] do
    collection do
      post 'add'
      post 'remove'
      post 'set_quantity'
      post 'clear'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  scope :top, -> { limit(10) }
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy

  scope :outdated, -> { where('updated_at < ?', 2.weeks.agoc) }
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_cart

  private

  def current_cart
    @_current_cart ||= Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    cart = Cart.create
    session[:cart_id] = cart.id
    cart
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.top
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  respond_to :js
  before_action :find_book, except: [:clear]

  def add
    @result = AddBookToCart.call(cart: current_cart, book: @book)
  end

  def remove
    RemoveBookFromCart.call(cart: current_cart, book: @book)
  end

  def set_quantity
    @result = SetBookQuantityInCart.call(cart: current_cart, book: @book, quantity: params[:quantity])
  end

  def clear
    ClearCart.call(cart: current_cart)
  end

  private

  def find_book
    @book = Book.find(params[:book_id])
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_book.html.slim
.col-md-3.col-sm-6.hero-feature class="js-book-#{book.id}"
  .thumbnail
    = image_tag 'http://placehold.it/800x500'
    .caption
      h3= book.name
      p= book.description
      p= link_to 'Buy Now!', add_cart_items_path(book_id: book), remote: true, method: :post, class: 'btn btn-primary js-add-to-cart'

app/views/books/index.html.slim
.row
  .col-lg-12
    h3 Books
.row.row-flex.text-center
  = render partial: 'book', collection: @books

app/views/cart_items/add.js.slim
- if @result.success?
  | $(".js-book-#{params[:book_id]} .js-add-to-cart").addClass('btn-success').removeClass('btn-primary').text('Added!')
- else
  | alert("#{@result.message}");

app/views/cart_items/clear.js.slim
| Turbolinks.visit(window.location.href);

app/views/cart_items/remove.js.slim
| $(".js-book-#{params[:book_id]}").remove();
| $(".js-cart-total").text("#{current_cart.decorate.total}");

app/views/cart_items/set_quantity.js.slim
- if @result.success?
  | $('.js-cart-total').text("#{current_cart.decorate.total}");
- else
  | alert("#{@result.message}");

app/views/carts/_cart_item.html.slim
.row class="js-book-#{cart_item.book.id}"
  .col-xs-2
    = image_tag 'http://placehold.it/100x70', class: 'img-responsive'
  .col-xs-4
    h4.product-name
      strong= cart_item.decorate.name
    h4
      small= cart_item.decorate.description
  .col-xs-6
    .col-xs-6.text-right
      h6
        strong
          = cart_item.decorate.price
          span.text-muted  x
    .col-xs-4
      = number_field_tag 'quantity', cart_item.quantity, min: 1, max: 1000, class: 'form-control input-sm js-quantity-change', data: { id: cart_item.book.id }
    .col-xs-2
      = link_to remove_cart_items_path(book_id: cart_item.book), remote: true, method: :post, class: 'btn btn-link btn-xs' do
        span.glyphicon.glyphicon-trash

app/views/carts/index.html.slim
.row
  .col-xs-8
    .panel.panel-info
      .panel-heading
        .panel-title
          .row
            .col-xs-6
              h5
                span.glyphicon.glyphicon-shopping-cart
                |  Shopping Cart
            .col-xs-6
              = link_to root_path, class: 'btn btn-primary btn-sm btn-block' do
                span.glyphicon.glyphicon-share-alt
                |  Continue shopping
      .panel-body
        - if current_cart.cart_items.any?
          = render partial: 'cart_item', collection: current_cart.cart_items
        - else
          .row.text-center
            | There's no items in the cart
      - if current_cart.cart_items.any?
        .panel-footer
          .row.text-center
            .col-xs-3
              = link_to 'Clear Cart', clear_cart_items_path, remote: true, method: :post, class: 'btn btn-danger btn-block'
            .col-xs-6
              h4.text-right
                = 'Total '
                strong.js-cart-total = current_cart.decorate.total
            .col-xs-3
              = link_to 'Checkout', '#', class: 'btn btn-success btn-block'

app/views/layouts/application.html.slim
doctype html
html
  head
    title Books Store
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
  body
    nav.navbar.navbar-inverse.navbar-fixed-top role='navigation'
      .container
        .navbar-header
          button.navbar-toggle data-target='#bs-example-navbar-collapse-1' data-toggle='collapse' type='button'
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to 'Books Store', root_path, class: 'navbar-brand'
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          ul.nav.navbar-nav
            li
              = link_to 'Cart', cart_index_path
    .container
      = yield